name       : ffms2
version    : 2.23
release    : 2
source     :
    - https://github.com/FFMS/ffms2/archive/2.23.tar.gz : b09b2aa2b1c6f87f94a0a0dd8284b3c791cbe77f0f3df57af99ddebcd15273ed
license    : MIT
component  : multimedia.library
summary    : An FFmpeg based source library and Avisynth/VapourSynth plugin for easy frame accurate access 
description: |
    An FFmpeg based source library and Avisynth/VapourSynth plugin for easy frame accurate access 
builddeps  :
    - pkgconfig(libavcodec)
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
